openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
paths:
  /ws/messages:
    get:
      responses:
        200:
          description: Returns messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    MessageToServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentCommand"
      discriminator:
        propertyName: type
    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummaryList"
        - $ref: "#/components/schemas/IncidentEvent"

    IncidentCommand:
      properties:
        incidentId:
          type: string
          format: uuid
        eventTime:
          type: string
          format: date-time
        delta:
          $ref: "#/components/schemas/IncidentDelta"
      required: [incidentId, eventTime, delta]

    IncidentEvent:
      allOf:
        - $ref: "#/components/schemas/IncidentCommand"
        - properties:
            timestamp:
              type: integer
              format: int64
            username:
              type: string
          required: [timestamp]

    IncidentDelta:
      oneOf:
        - $ref: "#/components/schemas/CreateIncident"
        - $ref: "#/components/schemas/UpdateIncident"
      discriminator:
        propertyName: delta

    CreateIncident:
      properties:
        info: { $ref: "#/components/schemas/IncidentInfo" }
      required: [info]
    UpdateIncident:
      properties:
        info: { $ref: "#/components/schemas/IncidentInfo" }
      required: [info]

    IncidentSummaryList:
      properties:
        incidents:
          type: array
          items:
            $ref: "#/components/schemas/IncidentSummary"
        lastTimestamp:
          type: integer
          format: int64
      required: [incidents, lastTimestamp]

    IncidentSummary:
      properties:
        incidentId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [incidentId, createdAt, updatedAt, info]

    IncidentInfo:
      properties:
        title:
          type: string
        priority:
          enum: [HIGH, MEDIUM, LOW]
