openapi: 3.1.0
info:
  title: My service
  description: My service
  version: 1.0.0
paths:
  /ws/messages:
    get:
      responses:
        200:
          description: Returns messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/MessageSummary"

    MessageSummary:
      properties:
        messageText:
          type: string
