openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
paths:
  /ws/messages:
    get:
      responses:
        200:
          description: Returns messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    MessageToServer:
      oneOf: []
      discriminator:
        propertyName: type
    MessageFromServer:
      oneOf: []
